### ISSUE TITLE
D10.2.3

### ISSUE THREAD

**Issue by limelect** [marcocantu/cantools#1]
On D10.2.3 on EditDirDblClick(
SelectDirectory (sDir, []); is not compatible with my Delphi
from embarcadero
FileCtrl.SelectDirectory(Dir, [sdAllowCreate, sdPerformCreate, sdPrompt],SELDIRHELP)

**Comment by BoscoBecker** [comment]
> On D10.2.3 on EditDirDblClick( SelectDirectory (sDir, []); is not compatible with my Delphi from embarcadero FileCtrl.SelectDirectory(Dir, [sdAllowCreate, sdPerformCreate, sdPrompt],SELDIRHELP)

Add Uses 
Vcl.FileCtrl, see more  > http://docwiki.embarcadero.com/Libraries/Sydney/en/Vcl.FileCtrl.SelectDirectory

**Comment by marcocantu** [comment]
I think this no longer applies
